server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: ${DB_USERNAME:bankcards}
    password: ${DB_PASSWORD:bankcards}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET:aGVsbG8gdGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCByYW5kb20gc2VjcmV0IGZvciB0ZXN0aW5nIHB1cnBvc2Vz}
  expiration-ms: 86400000

card:
  number-hash-salt: ${CARD_HASH_SALT:bankcards-default-salt-value}
